---
- name: Deploy Scientific Calculator using Docker
  hosts: local
  become: yes
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: aryannukala/scientific-calculator
        tag: latest
        source: pull
        
    - name: Stop and remove existing container if running
      docker_container:
        name: scientific-calculator-container
        state: absent
      ignore_errors: yes
      
    - name: Run Scientific Calculator container
      docker_container:
        name: scientific-calculator-container
        image: /scientific-calculator:latest
        state: started
        interactive: yes
        tty: yes
        detach: no
